apiVersion: v1
kind: ConfigMap
metadata:
  name: rag-app-config
  namespace: rag-system
  labels:
    app.kubernetes.io/name: agentic-multimodal-rag
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: config
data:
  # Application Configuration
  NODE_ENV: "production"
  APP_NAME: "agentic-multimodal-rag"
  APP_VERSION: "1.0.0"
  APP_PORT: "8000"
  APP_HOST: "0.0.0.0"
  DEBUG: "false"
  LOG_LEVEL: "info"
  
  # Milvus Configuration
  MILVUS_HOST: "milvus.milvus.svc.cluster.local"
  MILVUS_PORT: "19530"
  
  # MinIO Configuration
  MINIO_HOST: "minio.minio.svc.cluster.local"
  MINIO_PORT: "80"
  MINIO_SECURE: "false"
  MINIO_BUCKET: "rag-docs"
  MINIO_REGION: "us-east-1"
  
  # PostgreSQL Configuration
  POSTGRES_HOST: "pg-rw.pg.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "postgres"
  POSTGRES_SSL: "false"
  POSTGRES_POOL_MIN: "2"
  POSTGRES_POOL_MAX: "10"
  POSTGRES_CONNECTION_TIMEOUT: "60000"
  
  # Redis Configuration
  REDIS_HOST: "redis-simple.redis-new.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_POOL_SIZE: "10"
  REDIS_CONNECT_TIMEOUT: "10000"
  REDIS_COMMAND_TIMEOUT: "5000"
  
  # Neo4j Configuration
  NEO4J_URI: "bolt://neo4j.neo4j.svc.cluster.local:7687"
  NEO4J_USER: "neo4j"
  NEO4J_HTTP_URI: "http://neo4j.neo4j.svc.cluster.local:7474"
  
  # AI Models Configuration
  HF_HOME: "/opt/ai-models"
  TRANSFORMERS_CACHE: "/opt/ai-models"
  MODEL_DIR: "/opt/ai-models"
  JINA_MODEL_NAME: "jinaai/jina-embeddings-v2-base-en"
  NOMIC_MODEL_NAME: "nomic-ai/colnomic-embed-multimodal-7b"
  WHISPER_MODEL_NAME: "openai/whisper-base"
  
  # Feature Flags
  FEATURE_AGENTIC_REASONING: "true"
  FEATURE_TEMPORAL_KNOWLEDGE: "true"
  FEATURE_VECTOR_SEARCH: "true"
  FEATURE_MULTIMODAL: "true"
  FEATURE_GRAPH_EXPANSION: "true"
  FEATURE_EDGE_GRAPH: "true"
  
  # Edge Graph Configuration
  EDGE_GRAPH_CONFIG_PATH: "config/edge_graph.yaml"
  EDGE_GRAPH_HOT_RELOAD: "true"
  
  # File Processing Configuration
  MAX_FILE_SIZE: "104857600"
  ALLOWED_FILE_TYPES: "pdf,txt,docx,jpg,png,mp3,mp4,csv"
  TEMP_DIR: "/tmp/rag-uploads"
  
  # Embedding Configuration
  EMBEDDING_DIMENSION: "1024"
  CHUNK_SIZE: "512"
  CHUNK_OVERLAP: "102"
  SEARCH_TOP_K: "10"
  SEARCH_METRIC_TYPE: "IP"
  
  # Caching Configuration
  CACHE_TTL: "3600"
  CACHE_MAX_SIZE: "1000"
  CACHE_ENABLED: "true"
  
  # Performance Configuration
  WORKER_PROCESSES: "4"
  WORKER_CONNECTIONS: "1000"
  KEEPALIVE_TIMEOUT: "65"
  CLIENT_MAX_BODY_SIZE: "100M"
  
  # Security Configuration
  ALLOWED_HOSTS: "localhost,127.0.0.1,192.168.0.0/16"
  SECURE_SSL_REDIRECT: "false"
  SECURE_HSTS_SECONDS: "0"
  SECURE_HSTS_INCLUDE_SUBDOMAINS: "false"
  SECURE_HSTS_PRELOAD: "false"
  
  # CORS Configuration
  CORS_ORIGIN: "http://localhost:3000,http://localhost:3001"
  CORS_CREDENTIALS: "true"
  
  # Logging Configuration
  LOG_FORMAT: "json"
  LOG_FILE_ENABLED: "true"
  LOG_FILE_PATH: "./logs/app.log"
  LOG_MAX_FILES: "5"
  LOG_MAX_SIZE: "10m"
  
  # Rate Limiting
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX_REQUESTS: "100"
  RATE_LIMIT_SKIP_SUCCESSFUL_REQUESTS: "false"
  
  # Development Configuration
  HOT_RELOAD: "false"
  API_DOCS_ENABLED: "true"
  API_DOCS_PATH: "/docs"
  
  # Testing
  TEST_DB_NAME: "rag_test_db"
  TEST_REDIS_DB: "1"
  
  # Deployment Configuration
  CONTAINER_PORT: "8000"
  HEALTH_CHECK_ENDPOINT: "/health"
  READINESS_CHECK_ENDPOINT: "/ready"
  
  # Kubernetes
  K8S_NAMESPACE: "rag-system"
  K8S_SERVICE_NAME: "rag-app-service"
