apiVersion: v1
kind: Namespace
metadata:
  name: rag-system
  labels:
    name: rag-system
    app.kubernetes.io/name: agentic-multimodal-rag
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: namespace
