apiVersion: v1
kind: ServiceAccount
metadata:
  name: rag-app-sa
  namespace: rag-system
  labels:
    app.kubernetes.io/name: agentic-multimodal-rag
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: rag-system
  name: rag-app-role
  labels:
    app.kubernetes.io/name: agentic-multimodal-rag
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "events", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors"]
  verbs: ["get", "create"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rag-app-rolebinding
  namespace: rag-system
  labels:
    app.kubernetes.io/name: agentic-multimodal-rag
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: rolebinding
subjects:
- kind: ServiceAccount
  name: rag-app-sa
  namespace: rag-system
roleRef:
  kind: Role
  name: rag-app-role
  apiGroup: rbac.authorization.k8s.io
